# GKE Cluster Configuration
cluster:
  name: ${CLUSTER_NAME}
  zone: ${ZONE}
  initialNodeCount: ${NODE_COUNT}
  nodeConfig:
    machineType: ${MACHINE_TYPE}
    diskSizeGb: ${DISK_SIZE}
    oauthScopes:
      - https://www.googleapis.com/auth/devstorage.read_only
      - https://www.googleapis.com/auth/logging.write
      - https://www.googleapis.com/auth/monitoring
      - https://www.googleapis.com/auth/servicecontrol
      - https://www.googleapis.com/auth/service.management.readonly
      - https://www.googleapis.com/auth/trace.append
